# Generated by Django 3.0.8 on 2020-07-23 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Covid',
            fields=[
                ('Date', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('RequiringICUCovidCases', models.CharField(max_length=45)),
                ('CommunityTransmission', models.CharField(max_length=45)),
                ('TotalConfirmedCovidCases', models.CharField(max_length=45)),
                ('TotalCovidDeaths', models.CharField(max_length=45)),
                ('ConfirmedCovidCases', models.CharField(max_length=45)),
                ('ConfirmedCovidDeaths', models.CharField(max_length=45)),
                ('CloseContact', models.CharField(max_length=45)),
                ('StatisticsProfileDate', models.CharField(max_length=45)),
                ('FID', models.CharField(max_length=45)),
                ('TravelAbroad', models.CharField(max_length=45)),
                ('HospitalisedCovidCases', models.CharField(max_length=45)),
                ('timestamp', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Currentweather',
            fields=[
                ('dt', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('temp', models.CharField(max_length=45)),
                ('temp_min', models.CharField(max_length=45)),
                ('temp_max', models.CharField(max_length=45)),
                ('pressure', models.CharField(max_length=45)),
                ('humidity', models.CharField(max_length=45)),
                ('wind_speed', models.CharField(max_length=45)),
                ('wind_deg', models.CharField(max_length=45)),
                ('clouds_all', models.CharField(max_length=45)),
                ('weather_id', models.CharField(max_length=45)),
                ('weather_main', models.CharField(max_length=45)),
                ('weather_description', models.CharField(max_length=45)),
                ('weather_icon', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Forecastweather',
            fields=[
                ('dt', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('dt_iso', models.DateField()),
                ('temp', models.CharField(max_length=45)),
                ('temp_min', models.CharField(max_length=45)),
                ('temp_max', models.CharField(max_length=45)),
                ('pressure', models.CharField(max_length=45)),
                ('humidity', models.CharField(max_length=45)),
                ('wind_speed', models.CharField(max_length=45)),
                ('wind_deg', models.CharField(max_length=45)),
                ('clouds_all', models.CharField(max_length=45)),
                ('weather_id', models.CharField(max_length=45)),
                ('weather_main', models.CharField(max_length=45)),
                ('weather_description', models.CharField(max_length=45)),
                ('weather_icon', models.CharField(max_length=45)),
            ],
        ),
    ]
