# Generated by Django 3.0.8 on 2020-07-23 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='covid',
            name='timestamp',
        ),
    ]
