# Generated by Django 3.0.3 on 2020-07-22 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentweather',
            name='city_id',
        ),
        migrations.RemoveField(
            model_name='currentweather',
            name='city_name',
        ),
        migrations.RemoveField(
            model_name='currentweather',
            name='clouds_all',
        ),
        migrations.RemoveField(
            model_name='currentweather',
            name='dt_iso',
        ),
        migrations.RemoveField(
            model_name='currentweather',
            name='humidity',
        ),
        migrations.RemoveField(
            model_name='currentweather',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='currentweather',
            name='lon',
        ),
        migrations.RemoveField(
            model_name='currentweather',
            name='pressure',
        ),
        migrations.RemoveField(
            model_name='currentweather',
            name='temp_max',
        ),
        migrations.RemoveField(
            model_name='currentweather',
            name='temp_min',
        ),
        migrations.AlterField(
            model_name='currentweather',
            name='dt',
            field=models.CharField(max_length=45, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='currentweather',
            name='temp',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='currentweather',
            name='weather_description',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='currentweather',
            name='weather_icon',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='currentweather',
            name='weather_id',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='currentweather',
            name='weather_main',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='currentweather',
            name='wind_deg',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='currentweather',
            name='wind_speed',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
