# Generated by Django 3.0.8 on 2020-07-23 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0002_remove_covid_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covid',
            name='CloseContact',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='covid',
            name='CommunityTransmission',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='covid',
            name='ConfirmedCovidCases',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='covid',
            name='ConfirmedCovidDeaths',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='covid',
            name='FID',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='covid',
            name='HospitalisedCovidCases',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='covid',
            name='RequiringICUCovidCases',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='covid',
            name='StatisticsProfileDate',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='covid',
            name='TotalConfirmedCovidCases',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='covid',
            name='TotalCovidDeaths',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='covid',
            name='TravelAbroad',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='currentweather',
            name='clouds_all',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='currentweather',
            name='humidity',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='currentweather',
            name='pressure',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='currentweather',
            name='temp',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='currentweather',
            name='temp_max',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='currentweather',
            name='temp_min',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='currentweather',
            name='weather_description',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='currentweather',
            name='weather_icon',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='currentweather',
            name='weather_id',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='currentweather',
            name='weather_main',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='currentweather',
            name='wind_deg',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='currentweather',
            name='wind_speed',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='forecastweather',
            name='clouds_all',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='forecastweather',
            name='dt_iso',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='forecastweather',
            name='humidity',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='forecastweather',
            name='pressure',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='forecastweather',
            name='temp',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='forecastweather',
            name='temp_max',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='forecastweather',
            name='temp_min',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='forecastweather',
            name='weather_description',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='forecastweather',
            name='weather_icon',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='forecastweather',
            name='weather_id',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='forecastweather',
            name='weather_main',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='forecastweather',
            name='wind_deg',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='forecastweather',
            name='wind_speed',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
