# Generated by Django 3.0.3 on 2020-07-22 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0002_auto_20200722_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentweather',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='currentweather',
            name='dt',
            field=models.CharField(max_length=45),
        ),
    ]
