# Generated by Django 3.0.8 on 2020-07-23 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0004_covid_forecastweather'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='covid',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='currentweather',
            name='id',
        ),
        migrations.RemoveField(
            model_name='forecastweather',
            name='id',
        ),
        migrations.AddField(
            model_name='currentweather',
            name='clouds_all',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='currentweather',
            name='humidity',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='currentweather',
            name='pressure',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='currentweather',
            name='temp_max',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='currentweather',
            name='temp_min',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='forecastweather',
            name='clouds_all',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='forecastweather',
            name='dt_iso',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='forecastweather',
            name='humidity',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='forecastweather',
            name='pressure',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='forecastweather',
            name='temp_max',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='forecastweather',
            name='temp_min',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='covid',
            name='CloseContact',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='covid',
            name='CommunityTransmission',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='covid',
            name='ConfirmedCovidCases',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='covid',
            name='ConfirmedCovidDeaths',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='covid',
            name='FID',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='covid',
            name='HospitalisedCovidCases',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='covid',
            name='RequiringICUCovidCases',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='covid',
            name='StatisticsProfileDate',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='covid',
            name='TotalConfirmedCovidCases',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='covid',
            name='TotalCovidDeaths',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='covid',
            name='TravelAbroad',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='currentweather',
            name='dt',
            field=models.CharField(max_length=45, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='forecastweather',
            name='dt',
            field=models.CharField(max_length=45, primary_key=True, serialize=False),
        ),
    ]
