# Generated by Django 3.0.3 on 2020-07-06 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200706_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='leap_balance',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='leap_password',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='leap_username',
        ),
    ]
