# Generated by Django 3.0.3 on 2020-07-06 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200706_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='leap_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='profile',
            name='leap_password',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='leap_username',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
