# Generated by Django 3.0.3 on 2020-08-03 13:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0012_favouriteroutes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FavouriteRoutes',
            new_name='FavouriteDestinations',
        ),
    ]
