# Generated by Django 3.0.3 on 2020-08-05 13:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0015_auto_20200804_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favouritedestination',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='favouritedestination',
            unique_together={('user', 'name')},
        ),
    ]
