# Generated by Django 3.0.3 on 2020-08-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20200805_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='leap_password_binary',
            field=models.BinaryField(blank=True, default=b'', max_length=50),
        ),
    ]
