# Generated by Django 3.0.7 on 2020-08-09 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_profile_leap_password_binary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='leap_password',
        ),
    ]
